services:
  hugo:
    image: hugomods/hugo:exts
    command: server --bind 0.0.0.0 --baseURL http://localhost:1313 -D
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENV=development
    working_dir: /src
