baseURL = 'https://blackwell-systems.github.io/blog/'
languageCode = 'en-us'
title = 'Blackwell Systems Blog'
theme = 'nightfall'

[params]
  description = 'Technical writing on developer tools, AI workflows, and dotfiles'
  github = 'blackwell-systems'

[params.author]
  name = 'Blackwell Systems'

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
